### ISSUE TITLE
Light icons

### ISSUE THREAD

**Issue by VictorLeach96** [fomantic/create-fomantic-icons#1]
It would be nice to have light outline fonts for FA pro users. I am happy to do a PR for this.

`handshake alternative light outline icon`

Would this be acceptable?

**Comment by hammy2899** [comment]
I think this is a good idea but using `light` as a way to use light icons will cause a conflict with icons like `traffic light`, `traffic light stop`, `traffic light slow` etc. Maybe we could use `thin` so `handshake alternative thin outline icon`

**Comment by VictorLeach96** [comment]
How does the `static/aliases.json` work? can it be generated or do I need to manually go through and add icons which can be thin?

**Comment by hammy2899** [comment]
There is no way to automatically generate the aliases file. You shouldn't need to add lots of icons to the file, the file is purely for alias icons.

**Comment by VictorLeach96** [comment]
So I am going to need to go through every icon and add `thin: false/true` to every single one?

**Comment by hammy2899** [comment]
Ohh ok, I didn't think about that. I could do it for you if you give me 5-10mins.

**Comment by VictorLeach96** [comment]
Thanks, I have the rest of the code ready for a PR, it's just this part I was thinking it'd take a while to cross-reference every icon with fontawesome?

**Comment by hammy2899** [comment]
Ok so I have added `"thin": false/true` to all the aliases and add `true` to the ones which have light variants.

https://pastebin.com/d6eZejQL

**Comment by VictorLeach96** [comment]
There are 1,323 icons with light variation...

**Comment by VictorLeach96** [comment]
Thanks, ah I thought only some light icons were supported but it looks like they're 1:1 with bold and regular. Will get that done.

**Comment by VictorLeach96** [comment]
How does the aliases file relate to the total list on `https://fontawesome.com/icons?d=gallery`,
As there are icons which don't match up. Also is this a manual task to go through every icon keep them up to date?

**Comment by hammy2899** [comment]
The alias file isn't a list of all icons and they don't need to match up, its just a file of custom aliases for S/FUI.

**Comment by VictorLeach96** [comment]
So it maps missing FUI/FA4 icons to their counter parts in FA5?

**Comment by hammy2899** [comment]
For some icons yes and some are custom aliases from SUI.

**Comment by hammy2899** [comment]
@synoptase If you want to submit a PR feel free, it will be a big help.

**Comment by synoptase** [comment]
Sure, where do i start? Could you put me the files that need modification or the basic pseudo-code algorithm?

**Comment by cosminstefanxp** [comment]
Any updates on this?

**Comment by hammy2899** [comment]
@cosminstefanxp https://github.com/fomantic/icon-script/pull/3#issuecomment-464488222

**Comment by beatlecz** [comment]
Any update? I'm facing the problem how to deal with using light version of FA5Pro. And still not sure wether to wait for this update or invent custom solution :(

**Comment by hammy2899** [comment]
Added with new CLI

https://github.com/fomantic/create-fomantic-icons
