### ISSUE TITLE
where do i put the icons? using semantic-ui-react

### ISSUE THREAD

**Issue by the-vampiire** [fomantic/create-fomantic-icons#12]
thank you for writing this tool. i am wondering where i should save the icons to be used in semantic-ui-react?

also to be clear will i be able to use the newer icons with the `name` prop on `<Icon>`?

**Comment by hammy2899** [comment]
You will have to install `fomantic-ui` and create a theme with the `icon.overrides` file and then build it.

**Comment by hammy2899** [comment]
@the-vampiire Are you still having issues or can I close this now?

**Comment by the-vampiire** [comment]
sorry i didnt reply sooner i was working on something else. ill close it and have a go with your suggestion. thanks again
