### ISSUE TITLE
Using PRO fonts without a subscription

### ISSUE THREAD

**Issue by cosminstefanxp** [fomantic/create-fomantic-icons#126]
I have a perpetual license for FontAwesome Pro, so I can download the archive manually from their website:
![image](https://user-images.githubusercontent.com/1536594/96716617-f07e2180-13ad-11eb-8726-abf0e7bf3c3d.png)

However, since I don't have the subscription, I can't link my Github account. Is there any way I can use `create-fomantic-icons` with an archive I download manually (i.e. `fontawesome-pro-5.15.1-web.zip`)?

**Comment by hammy2899** [comment]
Currently no you can't however I may have a loop hole you could use to bypass the GitHub download the CLI does.

Can you tell me what the directory structure and contents of the zip you have access to is please.

**Comment by cosminstefanxp** [comment]
That would be really great and probably useful for many other people. Here's the folder structure:
<img width="278" alt="image" src="https://user-images.githubusercontent.com/1536594/96841075-fc242380-1453-11eb-8b45-f6aac982f278.png">
<img width="301" alt="image" src="https://user-images.githubusercontent.com/1536594/96841238-37265700-1454-11eb-9163-398a07cf1e55.png">

**Comment by hammy2899** [comment]
Ok you should be able to bypass this by doing the following

If your on Windows navigate to the following path
```
C:\Users\<username>\AppData\Local\Temp\fui-icon-script
```

Then put the downloaded zip into this directory and then rename it from `fontawesome-pro-5.15.1-web.zip` to `fontawesome-free-5.15.1-web.zip`. Then you should be able to run the CLI and select FontAwesome Free when it asks which version and it will use the cached download (the zip we just placed and renamed)

Let me know if you have any issues

**Comment by cosminstefanxp** [comment]
This worked great, thank you very much. With the following additions, in case someone else has this issue:
1. On MacOS, the temporary folder is `$TMPDIR` (`echo $TMPDIR`);
2. You need to also extract the zip archive in that temporary directory, making sure it's in a subdirectory like: `fui-icon-script/fontawesome-free-5.15.1-web/fontawesome-free-5.15.1-web/`;

**Comment by indreksiitan** [comment]
Can we bring this topic back on the table? Starting from 6.0, the Pro version is not available on GitHub anymore, so there is currently no way for anyone to build 6.0 Pro fonts without these ugly hacks.

**Comment by mneuhaus** [comment]
download version of font-awesome you got a valid license for from the website, put it in your project and link it into npm like this:   

<img width="2720" height="472" alt="Image" src="https://github.com/user-attachments/assets/e09b832d-2a0c-4603-9a0b-984a1bfc7b3d" />
