### ISSUE TITLE
Add support for duotone icons

### ISSUE THREAD

**Issue by hammy2899** [fomantic/create-fomantic-icons#36]
Add support to add duotone icons which were added in [FA 5.10.0](https://github.com/FortAwesome/Font-Awesome-Pro/blob/c88a03c8ed03e8a13168df57a5b79a6bbb8b4771/CHANGELOG.md#5100---2019-07-29)

**Comment by testinfected** [comment]
Hey guys, any news on that? Any idea idea on what's involved to make it work?

Thanks,

**Comment by hammy2899** [comment]
@testinfected I've been working on a tool to do this however I just don't have the time right now to finish it so unfortunately I can't tell you when it will be available.

To add it to his CLI you will need to add the duo icon style to the parser and then also to templates etc its somewhat simple just a bit time consuming especially with all the testing.

**Comment by testinfected** [comment]
@hammy2899 Thanks for the quick reply. I might have a look at how it works

**Comment by pedobry** [comment]
I have added support for Duotone icons in my fork - https://github.com/pedobry/create-fomantic-icons

**Comment by testinfected** [comment]
@pedobry that's fantastic! Do you plan to submit a PR?

**Comment by testinfected** [comment]
Any news on that? We're currently using our own fork base on @pedobry 's one.

Instead of updating our fork to support FA 6, what can be done to merge the PR and have duotone support out of the box?

Thanks

**Comment by lubber-de** [comment]
The existing PR is not mergeable anymore, we may try to adopt the base changes to the current codebase, this possibly also needs changes in the FUI codebase.

**Comment by testinfected** [comment]
Thanks for the update @lubber-de

**Comment by testinfected** [comment]
I've submitted a PR for this.

The following changes are required on FomanticUI source to use the new duotone icons, see attached patches (warning: I had to add a .txt extension to attach patches)
[add_duotone_definitions.patch.txt](https://github.com/fomantic/create-fomantic-icons/files/9929541/add_duotone_definitions.patch.txt)
[add_duotone_variation.patch.txt](https://github.com/fomantic/create-fomantic-icons/files/9929543/add_duotone_variation.patch.txt)

**Comment by testinfected** [comment]
Related to #126 only pro versions 5 are listed for download. Any plan/idea how to get Pro v6 icons?

**Comment by lubber-de** [comment]
> The following changes are required on FomanticUI source to use the new duotone icons, see attached patches (warning: I had to add a .txt extension to attach patches) [add_duotone_definitions.patch.txt](https://github.com/fomantic/create-fomantic-icons/files/9929541/add_duotone_definitions.patch.txt) [add_duotone_variation.patch.txt](https://github.com/fomantic/create-fomantic-icons/files/9929543/add_duotone_variation.patch.txt)

Please see my review comments in #203

**Comment by testinfected** [comment]
I've updated the pull request and reworked positioning of the second layer on top of the first layer. It think it works better and is simpler this way.

I've also discovered that Duotone icons support swapping the primary/secondary color layers (see https://fontawesome.com/v5/docs/web/style/duotone-icons). That could be a future improvement.

**Comment by lubber-de** [comment]
#203 is merged now. We will publish a new release once also FUI 2.9.1 gets published, as it is a necessary relationship/dependency
